require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.git_toolkit")
require("items.widgets.music")
require("items.widgets.weather")
